# Generated by Django 3.2 on 2023-05-24 10:36

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Телефонный номер')),
                ('code', models.PositiveIntegerField(blank=True, verbose_name='код мобильного оператора')),
                ('tag', models.CharField(max_length=30, verbose_name='тег пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='дата начала рассылки')),
                ('text', models.TextField(verbose_name='текст сообщения')),
                ('end_date', models.DateTimeField(verbose_name='дата окончания рассылки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entity', to='entities.client')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='дата отправки сообщения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='entities.client')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='entities.entity')),
            ],
        ),
    ]
