# Generated by Django 3.2 on 2023-05-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.RemoveField(
            model_name='entity',
            name='client',
        ),
        migrations.AddField(
            model_name='entity',
            name='client',
            field=models.ManyToManyField(related_name='entity', to='entities.Client'),
        ),
    ]
